version: '3'

services: 
  frameboxfrontend:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./dist:/app/dist
    ports: 
      - 80:80