export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const ALERT = 'ALERT';
export const ALERT_CLOSE = 'ALERT_CLOSE';

export const RESOURCES_LATEST_LOAD = 'RESOURCES_LATEST_LOAD';
export const RESOURCES_LATEST_UNLOAD = 'RESOURCES_LATEST_UNLOAD';

export const RESOURCES_SEARCH = 'RESOURCES_SEARCH';
export const RESOURCES_SEARCH_UNLOAD = 'RESOURCES_SEARCH_UNLOAD';

export const RESOURCES_DETAILS_LOAD = 'RESOURCES_DETAILS_LOAD';
export const RESOURCES_DETAILS_UNLOAD = 'RESOURCES_DETAILS_UNLOAD';

export const RESOURCES_ADD_VIEWED = 'RESOURCES_ADD_VIEWED';
export const RESOURCES_REMOVE_VIEWED = 'RESOURCES_REMOVE_VIEWED';

export const REVIEWS_LATEST_LOAD = 'REVIEWS_LATEST_LOAD';
export const REVIEWS_LATEST_UNLOAD = 'REVIEWS_LATEST_UNLOAD';

export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_UNLOAD = 'PROFILE_UNLOAD';

export const PROFILE_REVIEWS_LOAD = 'PROFILE_REVIEWS_LOAD';
export const PROFILE_REVIEWS_UNLOAD = 'PROFILE_REVIEWS_UNLOAD';

export const PROFILE_UPDATE_LOAD = 'PROFILE_UPDATE_LOAD';
export const PROFILE_UPDATE_UNLOAD = 'PROFILE_UPDATE_UNLOAD';

export const VIEWED_LOAD = 'VIEWED_LOAD';
export const VIEWED_UNLOAD = 'VIEWED_UNLOAD';