export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const SET_ALERT = 'SET_ALERT';
export const UNSET_ALERT = 'UNSET_ALERT';

export const SET_LOADED_PROFILE = 'SET_LOADED_PROFILE';
export const UNSET_LOADED_PROFILE = 'UNSET_LOADED_PROFILE';

export const SET_LATEST_RESOURCES = 'SET_LATEST_RESOURCES';
export const UNSET_LATEST_RESOURCES = 'UNSET_LATEST_RESOURCES';

export const SET_SEARCH_RESORCES = 'SET_SEARCH_RESORCES';
export const UNSET_SEARCH_RESORCES = 'UNSET_SEARCH_RESORCES';

export const SET_LATEST_REVIEWS = 'SET_LATEST_REVIEWS';
export const UNSET_LATEST_REVIEWS = 'UNSET_LATEST_REVIEWS';
export const SET_PROFILE_REVIEWS = 'SET_PROFILE_REVIEWS';
export const UNSET_PROFILE_REVIEWS = 'UNSET_PROFILE_REVIEWS';

export const SET_VIEWED = 'SET_VIEWED';
export const UNSET_VIEWED = 'UNSET_VIEWED';