export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const SET_ALERT = 'SET_ALERT';
export const UNSET_ALERT = 'UNSET_ALERT';

export const SET_LOADED_PROFILE = 'SET_LOADED_PROFILE';
export const UNSET_LOADED_PROFILE = 'UNSET_LOADED_PROFILE';

export const SET_PROFILE_REVIEWS = 'SET_PROFILE_REVIEWS';
export const UNSET_PROFILE_REVIEWS = 'UNSET_PROFILE_REVIEWS';