export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const SET_ALERT = 'SET_ALERT';
export const UNSET_ALERT = 'UNSET_ALERT';

export const SET_LOADED_PROFILE = 'SET_LOADED_PROFILE';
export const UNSET_LOADED_PROFILE = 'UNSET_LOADED_PROFILE';

export const SET_LATEST_RESOURCES = 'SET_LATEST_RESOURCES';
export const UNSET_LATEST_RESOURCES = 'UNSET_LATEST_RESOURCES';

export const SET_SEARCH_RESORCES = 'SET_SEARCH_RESORCES';
export const UNSET_SEARCH_RESORCES = 'UNSET_SEARCH_RESORCES';

export const SET_RESOURCES_DETAILS = 'SET_RESOURCES_DETAILS';
export const UNSET_RESOURCES_DETAILS = 'UNSET_RESOURCES_DETAILS';

export const SET_RESOURCE_IS_VIEWED = 'SET_RESOURCE_IS_VIEWED';
export const UNSET_RESOURCE_IS_VIEWED = 'UNSET_RESOURCE_IS_VIEWED';

export const SET_RESOURCE_RATE_AVERAGE = 'SET_RESOURCE_RATE_AVERAGE';
export const UNSET_RESOURCE_RATE_AVERAGE = 'UNSET_RESOURCE_RATE_AVERAGE';

export const SET_RESOURCE_REVIEWS = 'SET_RESOURCE_REVIEWS';
export const UNSET_RESOURCE_REVIEWS = 'UNSET_RESOURCE_REVIEWS';

export const SET_RESOURCE_MY_REVIEW = 'SET_RESOURCE_MY_REVIEW';
export const UNSET_RESOURCE_MY_REVIEW = 'UNSET_RESOURCE_MY_REVIEW';

export const SET_LATEST_REVIEWS = 'SET_LATEST_REVIEWS';
export const UNSET_LATEST_REVIEWS = 'UNSET_LATEST_REVIEWS';

export const SET_PROFILE_REVIEWS = 'SET_PROFILE_REVIEWS';
export const UNSET_PROFILE_REVIEWS = 'UNSET_PROFILE_REVIEWS';

export const SET_PROFILE_UPDATING = 'SET_PROFILE_UPDATING';
export const UNSET_PROFILE_UPDATING = 'UNSET_PROFILE_UPDATING';

export const SET_VIEWED = 'SET_VIEWED';
export const UNSET_VIEWED = 'UNSET_VIEWED';